"""Init

Revision ID: 636dcb7b1cc8
Revises: 
Create Date: 2025-01-30 14:41:00.037033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636dcb7b1cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
