"""change pass

Revision ID: 795880880374
Revises: dac8db79b50c
Create Date: 2025-02-03 14:04:58.233716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795880880374'
down_revision = 'dac8db79b50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=False))
        batch_op.drop_column('_User__password')
        batch_op.drop_column('password_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_1', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('_User__password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
