"""add shop list

Revision ID: cf6f73360906
Revises: 3ab601ac653c
Create Date: 2025-01-30 15:47:48.621103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6f73360906'
down_revision = '3ab601ac653c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_list',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_list_prod_assoc',
    sa.Column('shop_list_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_list_id'], ['shop_list.id'], ),
    sa.PrimaryKeyConstraint('shop_list_id', 'product_id')
    )
    op.create_table('user_shopping_cart_assoc',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.drop_table('user_prod_assoc')
    with op.batch_alter_table('user_shop_list_assoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_list_id', sa.String(), nullable=False))
        batch_op.drop_constraint('user_shop_list_assoc_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop_list', ['shop_list_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_shop_list_assoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_shop_list_assoc_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.drop_column('shop_list_id')

    op.create_table('user_prod_assoc',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='user_prod_assoc_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_prod_assoc_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name='user_prod_assoc_pkey')
    )
    op.drop_table('user_shopping_cart_assoc')
    op.drop_table('shop_list_prod_assoc')
    op.drop_table('shop_list')
    # ### end Alembic commands ###
